// Copies build inputs from the rest of the hangar repo into public/, so the site never
// keeps its own fork of a diagram or a mark. Hangar's diagrams stay generated by
// tools/diagrams/build_hangar.py; this only copies what that generator already wrote.
//
// Glidepath's SVGs live in another repo, so they are vendored under vendor/glidepath/.
// If a sibling ../../glidepath checkout exists, they are refreshed from it first.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const web = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(web, '..');
const pub = join(web, 'public');

const fresh = (dir) => { rmSync(dir, { recursive: true, force: true }); mkdirSync(dir, { recursive: true }); };

// 1. Hangar's diagram-design pages: plan/, autopilot/, reference/.
const diagramsSrc = join(repo, 'docs/autopilot/diagrams');
const diagramsOut = join(pub, 'diagrams');
fresh(diagramsOut);
const SETS = ['plan', 'autopilot', 'reference'];
const hangar = [];
for (const set of SETS) {
  cpSync(join(diagramsSrc, set), join(diagramsOut, set), { recursive: true });
  for (const file of readdirSync(join(diagramsSrc, set)).filter((f) => f.endsWith('.html')).sort()) {
    const html = readFileSync(join(diagramsSrc, set, file), 'utf8');
    const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || file;
    const eyebrow = (html.match(/class="eyebrow"[^>]*>([^<]*)</) || [])[1] || '';
    const slug = file.replace(/\.html$/, '');
    hangar.push({ id: `${set}/${slug}`, set, num: slug.slice(0, 2), title: decode(title), eyebrow: decode(eyebrow), path: `diagrams/${set}/${file}`, kind: 'html' });
  }
}

// 2. Glidepath's SVG diagrams (vendored; refreshed from a sibling checkout if present).
const vendor = join(web, 'vendor/glidepath');
const sibling = resolve(repo, '../glidepath/docs');
if (existsSync(sibling)) {
  for (const sub of ['admin/diagrams', 'user/diagrams']) {
    const dir = join(sibling, sub);
    if (existsSync(dir)) for (const f of readdirSync(dir).filter((f) => f.endsWith('.svg'))) cpSync(join(dir, f), join(vendor, f));
  }
}
const glidepathOut = join(diagramsOut, 'glidepath');
fresh(glidepathOut);
const GLIDEPATH_TITLES = {
  'architecture-overview': 'Glidepath system overview',
  'chaining-sequence': 'Inter-stage chaining: how test gets triggered by build finishing',
  'multi-cluster-topology': 'Multi-cluster topology',
  'cicd-yaml-mapping': 'cicd.yaml fields, and what actually runs',
  'onboarding-sequence': 'Getting a new app onto the platform',
  'deploy-vs-release': 'Deploy vs. release: different questions, different rigor',
  'pipeline-flow': 'What you change, and what the platform owns',
};
const glidepath = [];
for (const f of readdirSync(vendor).filter((f) => f.endsWith('.svg')).sort()) {
  cpSync(join(vendor, f), join(glidepathOut, f));
  const slug = f.replace(/\.svg$/, '');
  glidepath.push({ id: `glidepath/${slug}`, set: 'glidepath', num: '', title: GLIDEPATH_TITLES[slug] || slug, eyebrow: 'Glidepath', path: `diagrams/glidepath/${f}`, kind: 'svg' });
}

// 3. Brand marks.
const marksOut = join(pub, 'marks');
fresh(marksOut);
cpSync(join(repo, 'brand/marks'), marksOut, { recursive: true });
cpSync(join(repo, 'docs/brand/hangar-social-preview.png'), join(pub, 'social-preview.png'));
const brandOut = join(pub, 'brand');
fresh(brandOut);
for (const f of ['hangar-brand-system.html', 'tower-release-matrix.html']) cpSync(join(repo, 'docs/brand', f), join(brandOut, f));

// 4. The manifest the pages render from.
writeFileSync(join(web, 'src/data/diagrams.generated.json'), JSON.stringify([...hangar, ...glidepath], null, 2) + '\n');
console.log(`sync-assets: ${hangar.length} Hangar diagrams, ${glidepath.length} Glidepath diagrams, marks copied`);

function decode(s) {
  return s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;|&rsquo;/g, "'").replace(/&quot;/g, '"').trim();
}
