// Copies build inputs from the rest of the hangar repo into public/, so the site never
// keeps its own fork of a diagram or a mark. Hangar's diagrams stay generated by
// tools/diagrams/build_hangar.py; this only copies what that generator already wrote.
//
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const web = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repo = resolve(web, '..');
const pub = join(web, 'public');

const fresh = (dir) => { rmSync(dir, { recursive: true, force: true }); mkdirSync(dir, { recursive: true }); };

// 1. Hangar's diagram-design pages: plan/, autopilot/, reference/.
const diagramsSrc = join(repo, 'docs/autopilot/diagrams');
const diagramsOut = join(pub, 'diagrams');
fresh(diagramsOut);
const SETS = ['plan', 'autopilot', 'reference'];
const hangar = [];
for (const set of SETS) {
  cpSync(join(diagramsSrc, set), join(diagramsOut, set), { recursive: true });
  for (const file of readdirSync(join(diagramsSrc, set)).filter((f) => f.endsWith('.html')).sort()) {
    const html = readFileSync(join(diagramsSrc, set, file), 'utf8');
    const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || file;
    const eyebrow = (html.match(/class="eyebrow"[^>]*>([^<]*)</) || [])[1] || '';
    const slug = file.replace(/\.html$/, '');
    hangar.push({ id: `${set}/${slug}`, set, num: slug.slice(0, 2), title: decode(title), eyebrow: decode(eyebrow), path: `diagrams/${set}/${file}` });
  }
}

// 2. Glidepath's diagrams, generated by the same tool into docs/glidepath/diagrams.
const glidepathSrc = join(repo, 'docs/glidepath/diagrams');
const glidepathOut = join(diagramsOut, 'glidepath');
cpSync(glidepathSrc, glidepathOut, { recursive: true });
const glidepath = [];
for (const file of readdirSync(glidepathSrc).filter((f) => f.endsWith('.html')).sort()) {
  const html = readFileSync(join(glidepathSrc, file), 'utf8');
  const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || file;
  const eyebrow = (html.match(/class="eyebrow"[^>]*>([^<]*)</) || [])[1] || '';
  const slug = file.replace(/\.html$/, '');
  glidepath.push({ id: `glidepath/${slug}`, set: 'glidepath', num: slug.slice(0, 2), title: decode(title), eyebrow: decode(eyebrow), path: `diagrams/glidepath/${file}` });
}

// 2b. Essay sets generated by the same tool: Crossplane (the Building Airframe essays) in
// docs/crossplane/diagrams, Service catalog (the Why Airframe essay) in docs/catalog/diagrams, Testing (the Testkube essay) in
// docs/testing/diagrams, and
// SLOs (the SLO feature doc) in docs/slo/diagrams, and Overview (high-level pictures, the home page's among them)
// in docs/overview/diagrams.
const essaySets = {};
for (const set of ['overview', 'crossplane', 'catalog', 'testing', 'slo']) {
  const src = join(repo, `docs/${set}/diagrams`);
  cpSync(src, join(diagramsOut, set), { recursive: true });
  essaySets[set] = [];
  for (const file of readdirSync(src).filter((f) => f.endsWith('.html')).sort()) {
    const html = readFileSync(join(src, file), 'utf8');
    const title = (html.match(/<title>([^<]*)<\/title>/) || [])[1] || file;
    const eyebrow = (html.match(/class="eyebrow"[^>]*>([^<]*)</) || [])[1] || '';
    const slug = file.replace(/\.html$/, '');
    essaySets[set].push({ id: `${set}/${slug}`, set, num: slug.slice(0, 2), title: decode(title), eyebrow: decode(eyebrow), path: `diagrams/${set}/${file}` });
  }
}
const { overview, crossplane, catalog, testing, slo } = essaySets;

// 3. Brand marks.
const marksOut = join(pub, 'marks');
fresh(marksOut);
cpSync(join(repo, 'brand/marks'), marksOut, { recursive: true });
cpSync(join(repo, 'docs/brand/hangar-social-preview.png'), join(pub, 'social-preview.png'));
const brandOut = join(pub, 'brand');
fresh(brandOut);
for (const f of ['hangar-brand-system.html', 'tower-release-matrix.html']) cpSync(join(repo, 'docs/brand', f), join(brandOut, f));

// 4. Architecture reviews: standalone pages in docs/reviews/, shown on /review/.
const reviewsOut = join(pub, 'reviews');
fresh(reviewsOut);
for (const f of readdirSync(join(repo, 'docs/reviews')).filter((f) => f.endsWith('.html'))) cpSync(join(repo, 'docs/reviews', f), join(reviewsOut, f));

// 5. The manifest the pages render from.
writeFileSync(join(web, 'src/data/diagrams.generated.json'), JSON.stringify([...overview, ...hangar, ...glidepath, ...crossplane, ...catalog, ...testing, ...slo], null, 2) + '\n');
console.log(`sync-assets: ${overview.length + hangar.length + glidepath.length + crossplane.length + catalog.length + testing.length + slo.length} diagrams, marks copied`);

function decode(s) {
  return s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;|&rsquo;/g, "'").replace(/&quot;/g, '"').trim();
}
